name: Build Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_TRON_GIT_TAG: GreatVoyage-v4.3.0
      JAVA_TRON_VERSION: 4.3.0

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build --build-arg JAVA_TRON_VERSION=${JAVA_TRON_GIT_TAG} -t sunstake/java-tron:${JAVA_TRON_VERSION} .
          docker tag zsmartex/tron-java:${JAVA_TRON_VERSION} zsmartex/tron-java:latest

      - name: Push Docker Image
        run: |
          docker push zsmartex/tron-java:${JAVA_TRON_VERSION}
          docker push zsmartex/tron-java:latest
